server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: management
          uri: http://localhost:8082
          predicates:
            - Path=, 
        - id: execute
          uri: http://localhost:8083
          predicates:
            - Path=, 
        - id: todolist
          uri: http://localhost:8084
          predicates:
            - Path=/todolists/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: management
          uri: http://management:8080
          predicates:
            - Path=, 
        - id: execute
          uri: http://execute:8080
          predicates:
            - Path=, 
        - id: todolist
          uri: http://todolist:8080
          predicates:
            - Path=/todolists/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
